services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: inf349
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  redis-worker:
    build: ./api
    command: flask worker
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      FLASK_APP: inf349.py
      FLASK_DEBUG: 1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: inf349
  flask:
    build: ./api
    #command: flask init-db
    #command: python inf349.py
    command: bash -c "flask init-db && flask run --host=0.0.0.0 --port=5000"
    #command: gunicorn inf349:app -b 0.0.0.0:5000 -w 1
    volumes:
      - ./api:/code
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - redis-worker
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: inf349
      REDIS_URL: redis://redis:6379/0
      FLASK_APP: inf349.py
      FLASK_DEBUG: 1
  react:
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - flask
    environment:
      FLASK_API_URL: http://flask:5000